# Generated by Django 5.1.5 on 2025-01-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="trailer_url",
        ),
        migrations.AddField(
            model_name="movie",
            name="release_year",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
