# Generated by Django 5.1.5 on 2025-01-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_remove_movie_release_date_remove_movie_trailer_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(default=2000),
        ),
    ]
