# Generated by Django 5.1.5 on 2025-01-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0003_movie_image_url_alter_movie_release_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.AlterField(
            model_name="movie",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(),
        ),
    ]
