# Generated by Django 5.1.5 on 2025-01-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0005_rent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rent",
            old_name="rented_at",
            new_name="rent_date",
        ),
    ]
